routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/my/jobs', 'HomeController@myJobs')->name('home.my_jobs');

Route::resources([
    'task' => 'TasksController',
    'comment' => 'CommentController',
]);


Route::group(['middleware' => 'check_admin'], function()
{
    Route::get('drafts', 'HomeController@drafts')->name('task.drafts')->middleware('check_admin');
    Route::get('closed', 'HomeController@closed')->name('task.closed')->middleware('check_admin');
    Route::get('assigned', 'HomeController@assigned')->name('task.assigned')->middleware('check_admin');

    Route::resources([
        'wiki' => 'WikiController',
    ]);
});



Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');


Route::get('login/facebook', 'Auth\LoginController@redirectFacebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleFacebookCallback');

Route::get('login/twitter', 'Auth\LoginController@redirectTwitter')->name('login.twitter');
Route::get('login/twitter/callback', 'Auth\LoginController@handleTwitterCallback');

Route::get('login/google', 'Auth\LoginController@redirectGoogle')->name('login.google');
Route::get('login/google/callback', 'Auth\LoginController@handleGoogleCallback');


Route::get('/task/{id}/assignee/toggle', 'TasksController@assigneeToggle')
    ->name('task.assignee.toggle')
    ->middleware('auth');


if (config('app.env') == 'development') {
    Route::get('/test2', 'HomeController@test2');
    Route::get('/test', function(){

        $task = \App\Task::find(3);
        $user = \Illuminate\Support\Facades\Auth::user();

        \App\Mail::to(User::find(1))
            ->send(new CommentSent(\App\Comment::find(1)));

        var_dump('');echo "web.php61";exit;
        $c = \App\Comment::find(1);
        $m = new \App\Mail\CommentSent($c);
        $m->build();

//    $task->assignee()->detach($user);
//    $task->assignee()->attach($user);
        $task->assignee()->toggle($user);

        $ass = $task->assignee()->get();

        foreach ($ass as $item) {
            var_dump($item->email);
        }
//    $user->roles()->detach($roleId);
//    $user->roles()->attach($roleId, ['expires' => $expires]);

        return 'end';
    });
}

app/Wiki.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wiki extends Model
{
    const VAL_TITLE = 'required';
    const VAL_LINK = 'required';

    protected $fillable = [
        'title',
        'link',
    ];

    //
}

app/Http/Controllers/WikiController.php
<?php

namespace App\Http\Controllers;

use App\Wiki;
use Illuminate\Http\Request;

class WikiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('wiki.index', ['wikies' => Wiki::get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        wiki::create($request->all());

        return redirect()->route('wiki.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Wiki  $wiki
     * @return \Illuminate\Http\Response
     */
    public function show(Wiki $wiki)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Wiki  $wiki
     * @return \Illuminate\Http\Response
     */
    public function edit(Wiki $wiki)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Wiki  $wiki
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Wiki $wiki)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Wiki  $wiki
     * @return \Illuminate\Http\Response
     */
    public function destroy(Wiki $wiki)
    {
        $wiki->delete();
        return redirect()->route('wiki.index');
    }
}

resources/views/wiki/index.blade.php
@extends('layout')


@section('content')
    <table class="table">
        <thead>
            <th>id</th>
            <th>title</th>
            <th>link</th>
            <th>actions</th>
        </thead>

        <tbody>
            @foreach($wikies as $wiki)
                <tr>
                    <td>{{$wiki->id}}</td>
                    <td>{{$wiki->title}}</td>
                    <td>{{$wiki->link}}</td>
                    <td>
                        <form action="{{route('wiki.destroy', $wiki->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="X" onclick="return confirm('Are you sure?')">
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <hr>

    <h4>Create new wiki</h4>
    <form action="{{route('wiki.store')}}" method="POST">
        @csrf

        <input type="hidden" name="" value="0">
        <div class="form-group">
            <label for="exampleInputEmail1">Title</label>
            <input type="text" name="title" class="form-control" value="{{''}}" autocomplete="off">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Link</label>
            <input type="text" name="link" class="form-control" value="{{''}}" autocomplete="off">
        </div>
        <button type="submit" class="btn btn-success form-btn">
            Create
        </button>
    </form>
@endsection