routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/my/jobs', 'HomeController@myJobs')->name('home.my_jobs');

Route::resources([
    'task' => 'TasksController',
    'comment' => 'CommentController',
]);


Route::group(['middleware' => 'check_admin'], function()
{
    Route::get('drafts', 'HomeController@drafts')->name('task.drafts')->middleware('check_admin');
    Route::get('closed', 'HomeController@closed')->name('task.closed')->middleware('check_admin');
    Route::get('assigned', 'HomeController@assigned')->name('task.assigned')->middleware('check_admin');

    Route::resources([
        'wiki' => 'WikiController',
    ]);
});



Auth::routes();

Route::get('logout', 'Auth\LoginController@logout');


Route::get('login/facebook', 'Auth\LoginController@redirectFacebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleFacebookCallback');

Route::get('login/twitter', 'Auth\LoginController@redirectTwitter')->name('login.twitter');
Route::get('login/twitter/callback', 'Auth\LoginController@handleTwitterCallback');

Route::get('login/google', 'Auth\LoginController@redirectGoogle')->name('login.google');
Route::get('login/google/callback', 'Auth\LoginController@handleGoogleCallback');


Route::get('/task/{id}/assignee/toggle', 'TasksController@assigneeToggle')
    ->name('task.assignee.toggle')
    ->middleware('auth');


if (config('app.env') == 'development') {
    Route::get('/test2', 'HomeController@test2');
    Route::get('/test', function(){

        $task = \App\Task::find(3);
        $user = \Illuminate\Support\Facades\Auth::user();

        \App\Mail::to(User::find(1))
            ->send(new CommentSent(\App\Comment::find(1)));

        var_dump('');echo "web.php61";exit;
        $c = \App\Comment::find(1);
        $m = new \App\Mail\CommentSent($c);
        $m->build();

//    $task->assignee()->detach($user);
//    $task->assignee()->attach($user);
        $task->assignee()->toggle($user);

        $ass = $task->assignee()->get();

        foreach ($ass as $item) {
            var_dump($item->email);
        }
//    $user->roles()->detach($roleId);
//    $user->roles()->attach($roleId, ['expires' => $expires]);

        return 'end';
    });
}

app/Task.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Task extends Model
{
    const VAL_TITLE = 'required';
    const VAL_TEXT = 'required';
    const VAL_OVERVIEW = 'required';

    const DEFAULT_PRICE = 10;

    protected $dates = ['deadline'];

    protected $attributes = [
        'status'    => 'draft',
        'price'     => self::DEFAULT_PRICE,
        'tags'      => 'php Laravel'
    ];

    protected $casts = [
//        'tags' => 'array'
    ];

    protected $fillable = [
        'title',
        'text',
        'footer',
        'overview',
        'tags',
        'price',
        'deadline',
        'status',
    ];

    public static function boot()
    {
        parent::boot();

        self::creating(function($model){
            // ... code here

        });

        self::creating(function($model){
            // ... code here

//            $model->tags = explode(' ', $model->tags);
        });

        self::updating(function($model){
            // ... code here

//            $model->tags = explode(' ', $model->tags);
        });
    }


    public function getFormattedDeadlineAttribute()
    {
        return Carbon::parse($this->deadline)->format('M d Y');
    }

    public function getHoursLeftAttribute()
    {
        return Carbon::now()->diffInHours(
            Carbon::parse($this->deadline)
        );
    }

    /**
     * Get the phone record associated with the user.
     */
    public function comments()
    {
        return $this->hasMany('App\Comment')->whereNull('parent_id');
    }

    public function commentAnswers()
    {
        return $this->hasMany('App\Comment')->whereNotNull('parent_id');
    }

    public function assignee()
    {
        return $this->belongsToMany('App\User');
    }

    public function getFormattedText()
    {
        $ret = [];
        $sum = '';

        $Parsedown = new \Parsedown();

        foreach (explode("\r\n", $this->text) as $item) {

            if (strpos($item, '===') === 0) {

                $matches = [];
                preg_match_all('/(\d{1,})/', $item, $matches);

                if (isset($matches[1])) {
                    $wikies = Wiki::whereIn('id', $matches[1])->get();

                    $sum .= '<p class="links-holder">Wiki: ';
                    foreach ($wikies as $wiki) {
                        $sum .= ' <a target="_blank" href="'.$wiki->link.'">'.$wiki->title.'</a> ';
                    }
                    $sum .= '</p>';
                }

            } else {

                if (strlen($item)>1) {

                    $sum .= $item;

                } else {
                    if (strlen($sum) > 1) {
                        $ret[] = $Parsedown->text($sum);
                        $sum = '';
                    }
                }
            }
        }

        if (strlen($sum) > 1) {
            $ret[] = $Parsedown->text($sum);
        }

        return $ret;
    }

    /**
     * @return string
     */
    public function getShortTextAttribute()
    {
        $ret = [];
        foreach (explode("\r\n", $this->text) as $item) {
            if (strpos($item, '===') === 0)
            {
                continue;
            }
            $ret[] = $item;
        }

        return implode("\r\n", $ret);
    }

    public function getIsAssignedAttribute()
    {
        if (!Auth::check()) {
            return false;
        }

        return $this->assignee()->find(Auth::user()->id) !== null;
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\CreateArticleRequest;
use App\Task;
use App\Wiki;
use function foo\func;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class TasksController extends Controller
{

    public function __construct()
    {
        $this->middleware('check_admin', ['except' => ['show', 'assigneeToggle']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $task = new Task();
        $task->price = Task::DEFAULT_PRICE;

        $data = session('create_task');

        if ($data) {
            $task->fill($data->toArray());
        }

        $wikies = Wiki::get();

        return view('tasks.create')->with(compact('task', 'wikies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateArticleRequest $request)
    {
        $task = Task::create($request->all());

        session()->forget('create_task');
        session()->flush();

        return redirect()->route('task.show', ['id' => $task->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $answers = [];
        $task = Task::findOrFail($id);

        if (Auth::check()) {

            if ($task->status !== 'open'
                and !$task->assignee()->find(Auth::user()->id)
                and !Auth::user()->isAdmin()) {
                    abort(404);
            }

            $task->with('comments');
            foreach ($task->commentAnswers()->with('owner')->get() as $comment) {
                if (!isset($answers[$comment->parent_id])) {
                    $answers[$comment->parent_id] = [];
                }
                $answers[$comment->parent_id][] = $comment;
            }
        } else {
            if ($task->status !== 'open') {
                abort(404);
            }
        }

        return view('tasks.show', [
            'task'      => $task,
            'answers'   => $answers,
            'comments'  => $task->comments
        ]);
    }

    /**
     * @param $id
     */
    public function assigneeToggle($id)
    {
        $task = Task::findOrFail($id);

        $task->assignee()->toggle(Auth::user());
        return redirect(route('task.show', ['id' => $task->id]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::findOrFail($id);
        $wikies = Wiki::get();

        return view('tasks.create')->with(compact('task', 'wikies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Task::findOrFail($id);

        $task->fill($request->all());
        $task->save();

        return redirect()->route('task.show', ['id' => $task->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tasks/admin-menu.blade.php
@auth
    @if (Auth::user()->isAdmin())
        <div class="admin-menu alert-info">
            <a class="btn btn-secondary btn-xs" href="{{route('task.edit', ['id' => $task->id])}}">Edit</a>
        </div>
    @endif
@endauth

resources/views/tasks/create.blade.php
@extends('layout')

@section('content')

<div class="col-md-8 col-sm-8 col-xs-12">
    <div class="main-content">
        <article>
            @if($task->id)
                <h4 class="page-title mt-1">
                    Update task
                    <a target="_blank" href="{{route('task.show', $task->id)}}">show</a>
                </h4>
            @else
                <h4 class="page-title mt-1">Create new task</h4>
            @endif

            <div class="form-body">
                <form action="{{$task->id ? route('task.update', ['id' => $task->id]) : route('task.store')}}" method="POST">
                    @csrf

                    @if($task->id)
                        @method('PUT')
                    @endif

                    <div class="form-group">
                        <label for="exampleInputText1">Title</label>
                        <input type="text" class="form-control" name="title" value="{{$task->title}}">
                        @if ($errors->has('title'))
                            <span class="help-block alert-warning">{{ $errors->first('title') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="overview">Task overview</label>
                        <textarea name="overview" class="form-control" rows="5">{{ $task->overview }}</textarea>
                        @if ($errors->has('overview'))
                            <span class="help-block alert-warning">{{ $errors->first('overview') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Task scope</label>
                        <textarea name="text" class="form-control" rows="20" placeholder="">{{$task->text}}</textarea>
                        @if ($errors->has('text'))
                            <span class="help-block alert-warning">{{ $errors->first('text') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Task footer</label>
                        <textarea name="footer" class="form-control" rows="5" placeholder="">{{$task->footer}}</textarea>
                        @if ($errors->has('footer'))
                            <span class="help-block alert-warning">{{ $errors->first('footer') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Price</label>
                        <input type="text" name="price" class="form-control" id="exampleInputEmail1" value="{{$task->price}}">
                        @if ($errors->has('price'))
                            <span class="help-block alert-warning">{{ $errors->first('price') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Tags</label>
                        <input type="text" name="tags" class="form-control" id="exampleInputEmail1" value="{{$task->tags}}">
                        @if ($errors->has('tags'))
                            <span class="help-block alert-warning">{{ $errors->first('tags') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="deadline">Deadline date</label>
                        <input type="text" class="form-control" id="deadline" name="deadline" value="{{$task->deadline}}" autocomplete="off">
                        @if ($errors->has('deadline'))
                            <span class="help-block alert-warning">{{ $errors->first('deadline') }}</span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="status">Status</label>

                        <select name="status" id="" class="form-control">
                            <option @if($task->status == 'draft') selected @endif  value="draft">Draft</option>
                            <option @if($task->status == 'open') selected @endif value="open">Open</option>
                            <option @if($task->status == 'assigned') selected @endif value="assigned">Assigned</option>
                            <option @if($task->status == 'closed') selected @endif value="closed">Closed</option>
                        </select>

                    </div>

                    <button type="submit" class="btn btn-success form-btn">
                        @if($task->id) Update @else Create @endif
                    </button>

                    <div>
                        <h4>Article example</h4>
                        <p>line1</p>
                        <p>=== 1 2 44</p>
                        <p>line2</p>
                        <p>=== 2,4,6</p>
                    </div>
                </form>
            </div>
        </article>
    </div><!-- main-content -->
</div>


<div class="col-md-4 col-sm-4 col-xs-12">
    <div class="main-content">

        <h4>Wiki <a target="_blank" href="/wiki">list</a></h4>
        <ul>
            @foreach($wikies as $wiki)
                <li>
                    {{$wiki->id}} -
                    <a target="_blank" href="{{$wiki->link}}">
                        {{$wiki->title}}
                    </a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

@endsection

@section('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('#deadline').datepicker({
                dateFormat: "yy-mm-dd"
            });
        });
    </script>
@endsection

resources/views/tasks/list.blade.php
@extends('layout')

@section('content')

    <div class="row row-offcanvas row-offcanvas-left tasks-list">
        @foreach ($tasks as $task)

            <div class="col-md-4 col-sm-6 col-xs-12 cart">
                <div class="main-content">
                    <article>
                        <a href="{{ route('task.show', ['id' => $task->id]) }}">
                            <h4 class="post-title">{{ $task->title }}</h4>
                        </a>

                        <div class="post-meta">
                            <div>
                                <span>
                                    <b>{{$task->price}}$</b>
                                </span>

                                @foreach(explode(' ', $task->tags) as $tag)
                                    <a href="#" class="tag btn btn-default btn-xs" type="button">{{ $tag }}</a>
                                @endforeach
                            </div>

                            <div class="mt-1">
                                <i class="fa fa-calendar-check-o post-meta-icon"></i>
                                {{$task->hours_left}} hours left ({{ $task->formatted_deadline }})
                            </div>
                        </div>

                        @include('tasks.admin-menu', ['task' => $task])

                        <div class="post-content">
                            {{ $task->short_text }}
                        </div>

                    </article>
                </div>
            </div>

        @endforeach
    </div>

@endsection

resources/views/tasks/show.blade.php
@extends('layout')

@section('content')
<div class="row row-offcanvas row-offcanvas-left">
    <div class="col-md-6 col-sm-12 col-xs-12">
        <a href="/">All jobs</a> / This one
    </div>
</div>

<div class="row row-offcanvas row-offcanvas-left">

    <div class="col-md-7 col-sm-12 col-xs-12">
        <div class="main-content">
            <article>
                <h3 class="post-title mt-1">
                    {{ $task->title }}
                    @auth
                        @if(Auth::user()->isAdmin() and $task->status != 'open')
                           ({{$task->status}})
                        @endif
                    @endauth
                </h3>

                <hr>

                <div class="post-content2">
                    {{ $task->overview }}
                </div>

                <h4 class="mt-3">Scope:</h4>

                @foreach($task->getFormattedText() as $issue)
                    <div class="post-content">{!! $issue !!}</div>
                @endforeach

                <h4 class="mt-3">Submission Guidelines:</h4>
                <div class="post-content">{!! $task->footer !!}</div>

            </article>

        </div><!-- main-content -->
    </div>

    <!--========================== Right-Sidebar ================================-->

    <div class="col-md-5 col-sm-12 col-xs-12">
        <div class="right-sidebar">
            <div class="righ-sidebar-body">

                <div class="post-meta">
                    <div class="mt-2">
                        <i class="fa fa-dollar-sign"></i>Compensation: <b>{{ $task->price }}$</b>
                    </div>

                    <div class="mt-2">
                        <i class="fa fa-calendar-check-o post-meta-icon"></i> <b>{{ $task->hours_left }} hours</b> left to deadline ({{ $task->formatted_deadline }})
                    </div>

                    <div class="mt-2">
                        @foreach(explode(' ', $task->tags) as $tag)
                            <a href="#" class="tag btn btn-default btn-xs" type="button">{{ $tag }}</a>
                        @endforeach
                    </div>
                </div>

                @include('tasks.admin-menu', ['task' => $task])

                <div class="task-register mt-1">
                    <a href="{{route('task.assignee.toggle', ['id' => $task->id])}}" class="btn btn-success btn-block @guest disabled @endguest">
                        @if($task->isAssigned)
                            Stop work
                        @else
                            Start work
                        @endif
                    </a>
                </div>

                <hr>

                @guest
                <div class="register-block">
                    <h5 class="text-center">To start work, please login/register first</h5>
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a class="sign" href="#signin" aria-controls="signin" role="tab" data-toggle="tab">sign in</a>
                        </li>
                        <li role="presentation">
                            <a class="sign" href="#signup" aria-controls="signup" role="tab" data-toggle="tab">sign up</a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="signin">
                            <ul class="user-dropdown">
                                <form action="/login" method="POST">
                                    @csrf
                                    <input type="hidden" name="taskId" value="{{ $task->id }}">

                                    <div class="login-area">
                                        <div class="form-group">
                                            <label for="exampleInputText1">Email</label>
                                            <input type="email" name="email" class="form-control">
                                            @if ($errors->has('email'))
                                                <div class="invalid-feedback alert alert-danger">
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </div>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Password</label>
                                            <input type="password" name="password" class="form-control">

                                            @if ($errors->has('password'))
                                                <div class="invalid-feedback alert alert-danger">
                                                    <strong>{{ $errors->first('password') }}</strong>
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="checkbox">
                                        <input id="option" type="checkbox" name="remember" value="option">
                                        <label for="option"><span><span></span></span>Keep me singed in</label>
                                        <a href="/password/reset" class="pull-right">Forgot?</a>
                                    </div>
                                    <div class="form-submit">
                                        <button type="submit" class="btn btn-success btn-block">Sign in</button>
                                    </div>
                                </form>
                            </ul><!-- /User-Dropdown-->
                        </div><!-- /#Sing in -->
                        <div role="tabpanel" class="tab-pane" id="signup">
                            <ul class="user-dropdown">
                                <form action="/register" method="POST">
                                    @csrf
                                    <input type="hidden" name="taskId" value="{{ $task->id }}">

                                    <div class="login-area">
                                        <div class="form-group">
                                            <label for="exampleInputText1">Username</label>
                                            <input type="text" name="name" class="form-control" id="exampleInputEmail1">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email Address</label>
                                            <input type="email" name="email" class="form-control" id="exampleInputEmail1">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Password</label>
                                            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                                        </div>
                                    </div>
                                    <div class="checkbox">
                                        <input id="option1" type="checkbox" name="field" value="option1">
                                        <label for="option1"><span><span></span></span>I accept Terms and Condition ?</label>
                                    </div>
                                    <div class="form-submit">
                                        <button type="submit" class="btn btn-success btn-block">Sign up</button>
                                    </div>
                                </form>
                            </ul><!-- /User-Dropdown-->
                        </div><!-- /#Sing up -->
                    </div><!-- /Tab-Content -->

                    <ul class="social-nav center-block mt-5">
                        <li><a href="{{ route('login.twitter') }}"><i class="fa fa-twitter twitter"></i></a></li>
                        <li><a href="{{ route('login.facebook') }}"><i class="fa fa-facebook facebook"></i></a></li>
                        <li><a href="{{ route('login.google') }}"><i class="fa fa-google-plus google-plus"></i></a></li>
                    </ul>
                </div>
                @endguest

                @auth
                    @if($task->isAssigned or Auth::user()->isAdmin())
                        @include('comments.list', [
                            'task' => $task,
                            'comments' => $task->comments,
                            'answers' => $answers,
                        ])
                    @endif
                @endauth
            </div><!-- Righ-sidebar-body -->
        </div><!-- Right-Sidebar -->
    </div>

</div>

@endsection

@section('js')
    <script type="text/javascript">
        var from_show = 1;

        $(document).ready(function() {
            // debugger;
        });

    </script>
@endsection